Exploração inicial dos dados

In [1]:
import pandas as pd

In [4]:
# Load review datasets
dfr1 = pd.read_csv('rotten_tomatoes_critic_reviews.csv')
dfr2 = pd.read_csv('rotten_tomatoes_movie_reviews.csv')
# Load movie datasets
dfm1 = pd.read_csv('rotten_tomatoes_movies_1.csv')
dfm2 = pd.read_csv('rotten_tomatoes_movies_2.csv')
# Check the shape of the datasets
print(dfr1.shape)
print(dfr2.shape)
print(dfm1.shape)
print(dfm2.shape)
# Display the first row of each dataset
for i in (dfr1, dfr2, dfm1, dfm2):
    display(i.head(1))

(1130017, 8)
(1444963, 11)
(17712, 22)
(143258, 16)

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...

,id,reviewId,creationDate,criticName,isTopCritic,originalScore,reviewState,publicatioName,reviewText,scoreSentiment,reviewUrl
0,beavers,1145982,2003-05-23,Ivan M. Lincoln,False,3.5/4,fresh,Deseret News (Salt Lake City),Timed to be just long enough for most youngste...,POSITIVE,http://www.deseretnews.com/article/700003233/B...

,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76

,id,title,audienceScore,tomatoMeter,rating,ratingContents,releaseDateTheaters,releaseDateStreaming,runtimeMinutes,genre,originalLanguage,director,writer,boxOffice,distributor,soundMix
0,space-zombie-bingo,Space Zombie Bingo!,50.0,NaN,NaN,NaN,NaN,2018-08-25,75.0,"Comedy, Horror, Sci-fi",English,George Ormrod,"George Ormrod,John Sabotta",NaN,NaN,NaN

Pré-processamento de dados

In [5]:
# Rename columns for consistency
dfr1.rename(columns={'rotten_tomatoes_link':'id'}, inplace=True)
dfm1.rename(columns={'rotten_tomatoes_link':'id'},  inplace=True)

In [6]:
dfr2.rename(columns={'criticName': 'critic_name', 'creationDate':'review_date', 'isTopCritic':'top_critic', 'publicatioName': 'publisher_name',
                      'reviewText': 'review_content','originalScore':'review_score', 'reviewState': 'review_type'}, inplace=True)
dfm2.rename(columns={'title':'movie_title'}, inplace=True)
# Check for missing values
print('DFR1 NULL')
display(dfr1.isnull().sum())
print('DFR2 NULL')
display(dfr2.isnull().sum())
# Drop unnecessary columns
dfr2.drop(columns=['reviewId','scoreSentiment','reviewUrl' ], inplace=True)
# Display the first two rows and data information
for i in dfr1, dfm1, dfr2, dfm2:
    display(i.head(2))
    display(i.info())

DFR1 NULL

id                     0
critic_name        18529
top_critic             0
publisher_name         0
review_type            0
review_score      305936
review_date            0
review_content     65806
dtype: int64

DFR2 NULL

id                     0
reviewId               0
review_date            0
critic_name            0
top_critic             0
review_score      435218
review_type            0
publisher_name         0
review_content     69225
scoreSentiment         0
reviewUrl         210925
dtype: int64

,id,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...
1,m/0814255,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff..."

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1130017 entries, 0 to 1130016
Data columns (total 8 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   id              1130017 non-null  object
 1   critic_name     1111488 non-null  object
 2   top_critic      1130017 non-null  bool
 3   publisher_name  1130017 non-null  object
 4   review_type     1130017 non-null  object
 5   review_score    824081 non-null   object
 6   review_date     1130017 non-null  object
 7   review_content  1064211 non-null  object
dtypes: bool(1), object(7)
memory usage: 61.4+ MB

None

,id,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
1,m/0878835,Please Give,Kate (Catherine Keener) and her husband Alex (...,Nicole Holofcener's newest might seem slight i...,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",2010-04-30,...,Sony Pictures Classics,Certified-Fresh,87.0,142.0,Upright,64.0,11574.0,44,123,19

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17712 entries, 0 to 17711
Data columns (total 22 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                17712 non-null  object
 1   movie_title                       17712 non-null  object
 2   movie_info                        17391 non-null  object
 3   critics_consensus                 9134 non-null   object
 4   content_rating                    17712 non-null  object
 5   genres                            17693 non-null  object
 6   directors                         17518 non-null  object
 7   authors                           16170 non-null  object
 8   actors                            17360 non-null  object
 9   original_release_date             16546 non-null  object
 10  streaming_release_date            17328 non-null  object
 11  runtime                           17398 non-null  float64
 12  production_company                17213 non-null  object
 13  tomatometer_status                17668 non-null  object
 14  tomatometer_rating                17668 non-null  float64
 15  tomatometer_count                 17668 non-null  float64
 16  audience_status                   17264 non-null  object
 17  audience_rating                   17416 non-null  float64
 18  audience_count                    17415 non-null  float64
 19  tomatometer_top_critics_count     17712 non-null  int64
 20  tomatometer_fresh_critics_count   17712 non-null  int64
 21  tomatometer_rotten_critics_count  17712 non-null  int64
dtypes: float64(5), int64(3), object(14)
memory usage: 3.0+ MB

None

,id,review_date,critic_name,top_critic,review_score,review_type,publisher_name,review_content
0,beavers,2003-05-23,Ivan M. Lincoln,False,3.5/4,fresh,Deseret News (Salt Lake City),Timed to be just long enough for most youngste...
1,blood_mask,2007-06-02,The Foywonder,False,1/5,rotten,Dread Central,It doesn't matter if a movie costs 300 million...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1444963 entries, 0 to 1444962
Data columns (total 8 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   id              1444963 non-null  object
 1   review_date     1444963 non-null  object
 2   critic_name     1444963 non-null  object
 3   top_critic      1444963 non-null  bool
 4   review_score    1009745 non-null  object
 5   review_type     1444963 non-null  object
 6   publisher_name  1444963 non-null  object
 7   review_content  1375738 non-null  object
dtypes: bool(1), object(7)
memory usage: 78.5+ MB

None

,id,movie_title,audienceScore,tomatoMeter,rating,ratingContents,releaseDateTheaters,releaseDateStreaming,runtimeMinutes,genre,originalLanguage,director,writer,boxOffice,distributor,soundMix
0,space-zombie-bingo,Space Zombie Bingo!,50.0,NaN,NaN,NaN,NaN,2018-08-25,75.0,"Comedy, Horror, Sci-fi",English,George Ormrod,"George Ormrod,John Sabotta",NaN,NaN,NaN
1,the_green_grass,The Green Grass,NaN,NaN,NaN,NaN,NaN,2020-02-11,114.0,Drama,English,Tiffany Edwards,Tiffany Edwards,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143258 entries, 0 to 143257
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    143258 non-null  object
 1   movie_title           142891 non-null  object
 2   audienceScore         73248 non-null   float64
 3   tomatoMeter           33877 non-null   float64
 4   rating                13991 non-null   object
 5   ratingContents        13991 non-null   object
 6   releaseDateTheaters   30773 non-null   object
 7   releaseDateStreaming  79420 non-null   object
 8   runtimeMinutes        129431 non-null  float64
 9   genre                 132175 non-null  object
 10  originalLanguage      129400 non-null  object
 11  director              139041 non-null  object
 12  writer                90116 non-null   object
 13  boxOffice             14743 non-null   object
 14  distributor           23001 non-null   object
 15  soundMix              15917 non-null   object
dtypes: float64(3), object(13)
memory usage: 17.5+ MB

None

PySpark for Preprocessing and Data Integration

In [1]:
from pyspark.sql import SparkSession
from pyspark.ml.feature import Tokenizer
from pyspark.sql.functions import regexp_replace, col

In [1]:
# Create a Spark session
spark = SparkSession.builder \
    .appName("New_NLP") \
    .config("spark.driver.memory", "4g") \
    .config("spark.executor.memory", "4g") \
    .getOrCreate()

# Create Spark DataFrames from pandas DataFrames
sp_dfr1 = spark.createDataFrame(dfr1)
sp_dfr2 = spark.createDataFrame(dfr2)
sp_dfm1 = spark.createDataFrame(dfm1)
sp_dfm2 = spark.createDataFrame(dfm2)

# Drop rows with missing values
sp_dfr1 = sp_dfr1.na.drop()
sp_dfr2 = sp_dfr2.na.drop()

NameError: name 'SparkSession' is not defined

In [ ]:
# Tokenize the review content
tokenizer = Tokenizer(inputCol="review_content", outputCol="tokens")
sp_dfr1 = tokenizer.transform(sp_dfr1)
sp_dfr2 = tokenizer.transform(sp_dfr2)

In [ ]:
# Remove non-alphanumeric characters from review content
sp_dfr1 = sp_dfr1.withColumn("review_content", regexp_replace(col("review_content"), "[^a-zA-Z0-9\s,;]", ""))
sp_dfr2 = sp_dfr2.withColumn("review_content", regexp_replace(col("review_content"), "[^a-zA-Z0-9\s,;]", ""))
# Display a sample of the transformed data
sp_dfr2.show(2)